# -*- coding: utf-8 -*-
{
    'name': "POS - Weighing Scale Integration",

    'summary': """
       Scan the vegetables / Fruits  / Meats weighing machine labels in POS and update the price into weighing machine .
        
       """,

    'description': """
         The module helps to categorize the products as PLU items( Vegetables / Fruits / Meat) and enables the Weighing Scale barcode scanning in POS.  Also the price changes can be updated using the PLU.txt file which is generated by Odoo
    """,

    'author': "Loyal It solutions PVT LTD",
    'website': "http://www.loyalitsolutions.com",
    'category': 'Point of Sale',
    'version': '18.0.1.0.0',
    'license': 'AGPL-3',
    'price': '60',
    'currency': 'EUR',
    'support': "support@loyalitsolutions.com",
    'depends': ['base', 'product', 'sale', 'point_of_sale'],
    'data': [
        'security/ir.model.access.csv',
        'views/views.xml',
        'views/templates.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],
    'images': ['static/description/banner.png'],
}
